# ./websocket/Dockerfile
FROM openjdk:17-jdk-slim
COPY concertTicket-websocket-0.0.1-SNAPSHOT.jar /app/concertTicket-websocket-0.0.1-SNAPSHOT.jar
WORKDIR /app
CMD ["java", "-jar", "concertTicket-websocket-0.0.1-SNAPSHOT.jar"]